# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/drmdrew/syncrets
    steps:
      - checkout
      - run: cat VERSION | sed "s/BUILD/$CIRCLE_BUILD_NUM/g" > VERSION
      - run: go get -v -t -d ./...
      - run: make build
      - run: go test -v ./...
