# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10-node-browsers
    working_directory: /go/src/github.com/drmdrew/syncrets
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Update VERSION file
          command: |
            if [ "$CIRCLE_BUILD_NUM" != "" ]; then
              cp VERSION VERSION.orig
              (cat VERSION.orig | sed s/BUILD/${CIRCLE_BUILD_NUM}/g) > VERSION
              echo "Updating VERSION: $(cat VERSION)"
            fi
      - run: go get -v -t -d ./...
      - run: make build
      - run: go test -v ./...
      - run: go test -tags=integration -run ^TestIntegration
